"use strict";
exports.__esModule = true;
var Vector_1 = require("./Vector");
var vector1 = new Vector_1.Vector(10, 10);
var vector2 = new Vector_1.Vector(10, 10);
vector1.print();
vector2.print();
console.log(vector1.add(vector2));
console.log(vector1.subs(vector2));
console.log(vector1.mult(vector2));
console.log(vector1.multn(2));
